cmd_local = {'!matlab  -nodesktop -minimize -nosplash -r Local_upstream&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_feed1&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_transfer1&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_mainline1&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_feed2&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_transfer2&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_mainline2&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_feed3&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_transfer3&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_mainline3&';...
'!matlab  -nodesktop -minimize -nosplash -r Local_splitter&'};

cmd_global = {'!matlab  -nodesktop -minimize -nosplash -r Global_upstream&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_feed1&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_transfer1&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_mainline1&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_feed2&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_transfer2&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_mainline2&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_feed3&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_transfer3&';...
'!matlab  -nodesktop -minimize -nosplash -r Global_mainline3&'...
'!matlab  -nodesktop -minimize -nosplash -r Global_splitter&';};

%eval(char(cmd_global(1)))